version: 2

models:
  - name: dim_employer
    description: "Employer dimension"
    columns:
      - name: employer_id
        tests:
          - not_null
          - unique

  - name: dim_auxilliary_attributes
    description: "Auxiliary attributes dimension"
    columns:
      - name: auxilliary_attributes_id
        tests:
          - not_null
          - unique
