version: 2

models:
  - name: dim_employer
    description: "Employer dimension"
    columns:
      - name: employer_id
        tests:
          - not_null
          - unique

  - name: dim_auxilliary_attributes
    description: "Auxiliary attributes dimension"
    columns:
      - name: auxilliary_attributes_id
        tests:
          - not_null
          - unique
  
  - name: dim_occupation
    description: "Occupation dimension"
    columns:
      - name: occupation_id
        description: "Unikt ID för ett yrke."
        tests:
          - not_null
          - unique


  - name: dim_job_details
    description: "Innehåller detaljerade beskrivningar av jobbannonser, inklusive språkkrav och löneinformation."
    columns:
      - name: job_details_id
        description: "Surrogate key baserat på jobbannonsens id."
        tests:
          - not_null
          - unique

      - name: headline
        description: "Rubrik för jobbannonsen."

      - name: description
        description: "Textuell beskrivning av arbetsuppgifterna."

      - name: description_html
        description: "HTML-version av jobbets beskrivning."

      - name: duration
        description: "Anställningens längd, om angiven."

      - name: salary_type
        description: "Typ av lön, exempelvis fast eller rörlig."

      - name: salary_description
        description: "Ytterligare beskrivning av lönevillkor."

      - name: working_hours_type
        description: "Typ av arbetstid, exempelvis heltid eller deltid."

      - name: scope_of_work_min
        description: "Minsta arbetsomfattning i procent."

      - name: scope_of_work_max
        description: "Största arbetsomfattning i procent."

      - name: must_have_languages
        description: "Språk som krävs för jobbet, aggregerade till en kommaseparerad lista."


  - name: fct_job_ads
    description: "Faktatabell för jobbannonser med länkar till dimensionstabeller."
    columns:
      - name: occupation_id
        description: "FK till dim_occupation."
        tests:
          - not_null
          - relationships:
              to: ref('dim_occupation')
              field: occupation_id
      - name: job_details_id
        description: "FK till dim_job_details."
        tests:
          - not_null
      - name: employer_id
        description: "FK till dim_employer."
        tests:
          - not_null
          - relationships:
              to: ref('dim_employer')
              field: employer_id
      - name: vacancies
        description: "Antal lediga tjänster."
      - name: relevance
        description: "Hur relevant annonsen är (för sortering)."
      - name: application_deadline
        description: "Sista ansökningsdatum."

    
  - name: mart_installation_drift_underhall
    description: "Mart för jobbannonser inom 'Installation, drift, underhåll'."
    columns:
      - name: job_details_id
        description: "ID för annonsdetaljer."
      - name: occupation_field
        description: "Yrkesområde (ska vara 'Installation, drift, underhåll')."

  - name: mart_kropps_och_skonhetsvard
    description: "Mart för jobbannonser inom 'Kropps- och skönhetsvård'."

  - name: mart_kultur_media_design
    description: "Mart för jobbannonser inom 'Kultur, media, design'."
