sources:
  - name: job_ads
    schema: staging
    tables:
      - name: stg_ads
        identifier: job_ads
        meta: 
          dagster: 
            asset_key: ['dlt_jobads_source_get_ads']
      - name: stg_must_have_languages
        identifier: job_ads__must_have__languages
     